version: '3.8'

services:
  # Backend Service
  backend:
    build:
      context: ./nix-pm-backend
      dockerfile: Dockerfile
    container_name: nix-pm-backend
    environment:
      # External PostgreSQL connection
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      # SMTP Configuration
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      # External Superset connection
      SUPERSET_URL: ${SUPERSET_URL}
      SUPERSET_USERNAME: ${SUPERSET_USERNAME}
      SUPERSET_PASSWORD: ${SUPERSET_PASSWORD}
      NODE_ENV: production
    ports:
      - "3001:3001"
    networks:
      - nix-pm-network
    restart: unless-stopped

  # Frontend Service
  frontend:
    build:
      context: ./nix-pm
      dockerfile: Dockerfile
    container_name: nix-pm-frontend
    environment:
      # External Superset URL (accessible from user browsers)
      SUPERSET_URL: ${SUPERSET_URL}
      # Backend API URL (can be relative in production with ingress)
      API_URL: /api
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - nix-pm-network
    restart: unless-stopped

networks:
  nix-pm-network:
    driver: bridge
